defaults:
  - override hydra/launcher: submitit_slurm

hydra:
  job:
    chdir: True
  launcher:
    submitit_folder: ${hydra.sweep.dir}/.submitit/%j
    nodes: 1
    tasks_per_node: 1
    cpus_per_task: 1
    mem_gb: 4
    timeout_min: 5
